### ISSUE TITLE
osmnx for street networks and spatial indexing

### ISSUE THREAD

**Issue by jhconning** [jeremysze/LPIS#2]
@jeremysze:  I don't know how you constructed your street intersections data but I came across a very nice method to do so, and learned a few speedup tricks along the way.   

I created a new examples folder for things like this and put a new [NYC_osmnx.ipynb](https://github.com/jeremysze/LPIS/blob/master/examples/NYC_osmnx.ipynb) notebook there with the details.

This may be not be needed at all for this project but the osmnx library apparently offers all types of network analysis tools, including finding shortest routes.

**Comment by mbaker21231** [comment]
@jhconning -

This is a great notebook. Lots of useful stuff here.

**Comment by jeremysze** [comment]
Thanks! I'm going to try to replicate this. Within QGIS, I loaded LION NYC street shapefile and looked for intersections of streets.

**Comment by jeremysze** [comment]
`G = ox.graph_from_bbox(north, south, east, west, network_type='drive', retain_all=True)`

I am getting errors at this command. The error says "RuntimeError: b'No such file or directory'"

**Comment by jeremysze** [comment]
Found a potential solution online. Hopefully it solves the issue.
[https://github.com/gboeing/osmnx/issues/203]

**Comment by jeremysze** [comment]
Fixed it with `import os
os.environ["PROJ_LIB"] = "C:\ProgramData\Anaconda3\Library\share" #window`

**Comment by jhconning** [comment]
I had the exact same problem, but only on my office computer.  I didn't think to mention it didn't affect my laptop computer,.  Something gone wrong with the recent pyproj installation.

**Comment by jeremysze** [comment]
I think the above file path might fix the issue for you
