### ISSUE TITLE
reading json from url

### ISSUE THREAD

**Issue by jhconning** [jeremysze/LPIS#4]
I noticed you didn't quite succeed at loading a dataframe from json via url in [your notebook](https://github.com/jeremysze/LPIS/blob/master/Export%20Traffic%20signal%20from%20Overpass%20API.ipynb).  

 This may no longer be needed as you got handed the traffic light data, but in case you need to anything else in json format here's how I'd do it: 

https://gist.github.com/jhconning/66c432d0d3239cdd4d3636fc98885625

The hard part of this is that the overpass OSM json data is 'nested'... the json file holds column data as dictionary data but one of the columns you'll extract from  `elements'  in turn has observations that are each dictionaries (it's like subvariables of the variable)..   So one has to 'flatten' the data.. the json_normalize utility helps to do that but can be  confusing to understand.. .without stackoverlow handy. The code at the gist shows my way to two step way to extract the data..

**Comment by jeremysze** [comment]
I was trying to do that! But I just didn't find the right resource/keyword (nested) to search for the solution! Thanks! I will try it out.

**Comment by jhconning** [comment]
Well as you can see (I updated the gist slightly)... I couldn't figure how to extract it all elegantly at one go either...  json is confusing stuff.

**Comment by jeremysze** [comment]
I've finally pulled the long and lat and turned the data into a geopandas df!
