### ISSUE TITLE
Very minor code suggestions

### ISSUE THREAD

**Issue by jhconning** [jeremysze/LPIS#5]
As I try to catch up on reading all your new code., this thread is to collect minor comments and code suggestions as I move through the notebooks:

In [Collisions to Signal intersections.ipynb](https://github.com/jeremysze/LPIS/blob/master/Collisions%20to%20Signal%20intersections.ipynb)

This is absolutely minor and non-essential and mentioned only just because it's fun to try to find shorter but still readable way to do things in python... You can save some typing on those type conversions:
```
str_cols = list(df1.select_dtypes(include=['object']).columns)
for col in str_cols:
    df1[col] = df1[col].astype(str)
```

**Comment by jhconning** [comment]
Another small suggestion/request:  Can you add a markdown file to the repo that explains the approximate order in which you would run all the notebooks?  

Perhaps eventually in the very end when everything is set and done you can use a utility like [papermill](https://github.com/nteract/papermill) to parameterize and then sequentially run all the notebooks in a chain.

**Comment by jeremysze** [comment]
I was starting to get confused myself. I've created [Command file](https://github.com/jeremysze/LPIS/blob/master/Command%20file.ipynb) so that the sequential files/steps can be followed.

**Comment by jhconning** [comment]
Comand file is useful. Thanks.. 

Actually, it just occurred to me, why do you even need to convert 'object' to 'string'? I thought 'object' is already a pandas string!?  I think if you check your dtypes again you'll find that they're again listed as 'object'!

**Comment by jeremysze** [comment]
Oh! Because I was trying to save out into stata dta, and it gives an error when I do so. I follow the [tips](https://www.maxmasnick.com/projects/scipy-tips/#initial-setup-for-ipython-notebooks) from this page to set up. Your loop is much more efficient than his. I think eventually I'm going to try to replicate most of the stata code into python and leave only the analysis to stata.

**Comment by jhconning** [comment]
Ah, you're right `to_stata` fails otherwise.
